Roc Wong, the head of Seele ecology.  Roc was one of the earliest college graduate entrepreneurs in China.  As a veteran investor and serial entrepreneur Roc had successfully established a number of enterprises.  Roc was also one of the pioneers in IDL visualization computer language and big data in China.  Since 2017, he has been a partner of the Encrypted Digital Money Fund, focusing on early project investments in blockchain technology.  He's also the head of the BCH ecological fund.<br>  
Sincerely<br><br>

Seele Team<br>

9/3/2019<br><br>

![Roc Wong](/images/roc_wong.jpg)